# Generated by Django 4.0.3 on 2023-07-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='id',
        ),
        migrations.AlterField(
            model_name='technician',
            name='employee_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
